version: "3.9"

services:
  db:
    image: postgres
    restart: always
  server: 
    build:
      context: ./
      target: development
    ports: 
      - 4002:4002
    env_file: ./.env
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    command: npm run dev

