version: "3.9"

services:
  server: 
    build:
      context: ./
      target: development
    ports: 
      - 4003:4003
    env_file: ./.env
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    command: npm run dev

